/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_RTIME_H
#define _MOCK_RTIME_H

#include "rtime.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mock_rtime_Init(void);
void Mock_rtime_Destroy(void);
void Mock_rtime_Verify(void);




#define rtime_get_IgnoreAndReturn(cmock_retval) rtime_get_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void rtime_get_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, Time* cmock_to_return);
#define rtime_get_ExpectAndReturn(cmock_retval) rtime_get_CMockExpectAndReturn(__LINE__, cmock_retval)
void rtime_get_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, Time* cmock_to_return);
typedef Time* (* CMOCK_rtime_get_CALLBACK)(int cmock_num_calls);
void rtime_get_StubWithCallback(CMOCK_rtime_get_CALLBACK Callback);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
