/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mock_adc.h"

static const char* CMockString_ADC_getSample = "ADC_getSample";
static const char* CMockString_channel = "channel";

typedef struct _CMOCK_ADC_getSample_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ADCSampleUnit ReturnVal;
  int CallOrder;
  int Expected_channel;
  int IgnoreArg_channel;

} CMOCK_ADC_getSample_CALL_INSTANCE;

static struct Mock_adcInstance
{
  int ADC_getSample_IgnoreBool;
  ADCSampleUnit ADC_getSample_FinalReturn;
  CMOCK_ADC_getSample_CALLBACK ADC_getSample_CallbackFunctionPointer;
  int ADC_getSample_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ADC_getSample_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void Mock_adc_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.ADC_getSample_IgnoreBool)
    Mock.ADC_getSample_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_ADC_getSample);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.ADC_getSample_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.ADC_getSample_CallbackFunctionPointer != NULL)
    Mock.ADC_getSample_CallInstance = CMOCK_GUTS_NONE;
}

void Mock_adc_Init(void)
{
  Mock_adc_Destroy();
}

void Mock_adc_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.ADC_getSample_CallbackFunctionPointer = NULL;
  Mock.ADC_getSample_CallbackCalls = 0;
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

ADCSampleUnit ADC_getSample(int channel)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ADC_getSample_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ADC_getSample);
  cmock_call_instance = (CMOCK_ADC_getSample_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ADC_getSample_CallInstance);
  Mock.ADC_getSample_CallInstance = CMock_Guts_MemNext(Mock.ADC_getSample_CallInstance);
  if (Mock.ADC_getSample_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.ADC_getSample_FinalReturn;
    memcpy(&Mock.ADC_getSample_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(ADCSampleUnit));
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_channel)
  {
    UNITY_SET_DETAILS(CMockString_ADC_getSample,CMockString_channel);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_channel, channel, cmock_line, CMockStringMismatch);
  }
  if (Mock.ADC_getSample_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.ADC_getSample_CallbackFunctionPointer(channel, Mock.ADC_getSample_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_ADC_getSample(CMOCK_ADC_getSample_CALL_INSTANCE* cmock_call_instance, int channel)
{
  cmock_call_instance->Expected_channel = channel;
  cmock_call_instance->IgnoreArg_channel = 0;
}

void ADC_getSample_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ADCSampleUnit cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_getSample_CALL_INSTANCE));
  CMOCK_ADC_getSample_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_getSample_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_getSample_CallInstance = CMock_Guts_MemChain(Mock.ADC_getSample_CallInstance, cmock_guts_index);
  Mock.ADC_getSample_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ADC_getSample_IgnoreBool = (int)1;
}

void ADC_getSample_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int channel, ADCSampleUnit cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_getSample_CALL_INSTANCE));
  CMOCK_ADC_getSample_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_getSample_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_getSample_CallInstance = CMock_Guts_MemChain(Mock.ADC_getSample_CallInstance, cmock_guts_index);
  Mock.ADC_getSample_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_ADC_getSample(cmock_call_instance, channel);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(ADCSampleUnit));
  UNITY_CLR_DETAILS();
}

void ADC_getSample_StubWithCallback(CMOCK_ADC_getSample_CALLBACK Callback)
{
  Mock.ADC_getSample_IgnoreBool = (int)0;
  Mock.ADC_getSample_CallbackFunctionPointer = Callback;
}

void ADC_getSample_CMockIgnoreArg_channel(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ADC_getSample_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_getSample_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ADC_getSample_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_channel = 1;
}

