/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_ADCONV_H
#define _MOCK_ADCONV_H

#include "adconv.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mock_adconv_Init(void);
void Mock_adconv_Destroy(void);
void Mock_adconv_Verify(void);




#define ADConv_getSample_IgnoreAndReturn(cmock_retval) ADConv_getSample_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void ADConv_getSample_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ADCSampleUnit cmock_to_return);
#define ADConv_getSample_ExpectAndReturn(channel, cmock_retval) ADConv_getSample_CMockExpectAndReturn(__LINE__, channel, cmock_retval)
void ADConv_getSample_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int channel, ADCSampleUnit cmock_to_return);
typedef ADCSampleUnit (* CMOCK_ADConv_getSample_CALLBACK)(int channel, int cmock_num_calls);
void ADConv_getSample_StubWithCallback(CMOCK_ADConv_getSample_CALLBACK Callback);
#define ADConv_getSample_IgnoreArg_channel() ADConv_getSample_CMockIgnoreArg_channel(__LINE__)
void ADConv_getSample_CMockIgnoreArg_channel(UNITY_LINE_TYPE cmock_line);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
