/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mock_epoch.h"

static const char* CMockString_epoch_get = "epoch_get";

typedef struct _CMOCK_epoch_get_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Epoch ReturnVal;
  int CallOrder;

} CMOCK_epoch_get_CALL_INSTANCE;

static struct Mock_epochInstance
{
  int epoch_get_IgnoreBool;
  Epoch epoch_get_FinalReturn;
  CMOCK_epoch_get_CALLBACK epoch_get_CallbackFunctionPointer;
  int epoch_get_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE epoch_get_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void Mock_epoch_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.epoch_get_IgnoreBool)
    Mock.epoch_get_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_epoch_get);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.epoch_get_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.epoch_get_CallbackFunctionPointer != NULL)
    Mock.epoch_get_CallInstance = CMOCK_GUTS_NONE;
}

void Mock_epoch_Init(void)
{
  Mock_epoch_Destroy();
}

void Mock_epoch_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.epoch_get_CallbackFunctionPointer = NULL;
  Mock.epoch_get_CallbackCalls = 0;
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

Epoch epoch_get(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_epoch_get_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_epoch_get);
  cmock_call_instance = (CMOCK_epoch_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.epoch_get_CallInstance);
  Mock.epoch_get_CallInstance = CMock_Guts_MemNext(Mock.epoch_get_CallInstance);
  if (Mock.epoch_get_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.epoch_get_FinalReturn;
    memcpy(&Mock.epoch_get_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(Epoch));
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.epoch_get_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.epoch_get_CallbackFunctionPointer(Mock.epoch_get_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void epoch_get_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, Epoch cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_epoch_get_CALL_INSTANCE));
  CMOCK_epoch_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_epoch_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.epoch_get_CallInstance = CMock_Guts_MemChain(Mock.epoch_get_CallInstance, cmock_guts_index);
  Mock.epoch_get_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.epoch_get_IgnoreBool = (int)1;
}

void epoch_get_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, Epoch cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_epoch_get_CALL_INSTANCE));
  CMOCK_epoch_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_epoch_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.epoch_get_CallInstance = CMock_Guts_MemChain(Mock.epoch_get_CallInstance, cmock_guts_index);
  Mock.epoch_get_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(Epoch));
  UNITY_CLR_DETAILS();
}

void epoch_get_StubWithCallback(CMOCK_epoch_get_CALLBACK Callback)
{
  Mock.epoch_get_IgnoreBool = (int)0;
  Mock.epoch_get_CallbackFunctionPointer = Callback;
}

