/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_EPOCH_H
#define _MOCK_EPOCH_H

#include "epoch.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mock_epoch_Init(void);
void Mock_epoch_Destroy(void);
void Mock_epoch_Verify(void);




#define epoch_get_IgnoreAndReturn(cmock_retval) epoch_get_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void epoch_get_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, Epoch cmock_to_return);
#define epoch_get_ExpectAndReturn(cmock_retval) epoch_get_CMockExpectAndReturn(__LINE__, cmock_retval)
void epoch_get_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, Epoch cmock_to_return);
typedef Epoch (* CMOCK_epoch_get_CALLBACK)(int cmock_num_calls);
void epoch_get_StubWithCallback(CMOCK_epoch_get_CALLBACK Callback);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
