/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mock_CirBuffer.h"

static const char* CMockString_cirBuffer_get = "cirBuffer_get";
static const char* CMockString_cirBuffer_getBlock = "cirBuffer_getBlock";
static const char* CMockString_cirBuffer_init = "cirBuffer_init";
static const char* CMockString_cirBuffer_put = "cirBuffer_put";
static const char* CMockString_destBlock = "destBlock";
static const char* CMockString_elem = "elem";
static const char* CMockString_elemSize = "elemSize";
static const char* CMockString_me = "me";
static const char* CMockString_nElem = "nElem";
static const char* CMockString_sto = "sto";

typedef struct _CMOCK_cirBuffer_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int CallOrder;
  CirBuffer* Expected_me;
  unsigned char* Expected_sto;
  int Expected_elemSize;
  int Expected_nElem;
  int IgnoreArg_me;
  int IgnoreArg_sto;
  int IgnoreArg_elemSize;
  int IgnoreArg_nElem;

} CMOCK_cirBuffer_init_CALL_INSTANCE;

typedef struct _CMOCK_cirBuffer_put_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int CallOrder;
  CirBuffer* Expected_me;
  unsigned char* Expected_elem;
  int IgnoreArg_me;
  int IgnoreArg_elem;

} CMOCK_cirBuffer_put_CALL_INSTANCE;

typedef struct _CMOCK_cirBuffer_get_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int CallOrder;
  CirBuffer* Expected_me;
  unsigned char* Expected_elem;
  int IgnoreArg_me;
  int IgnoreArg_elem;

} CMOCK_cirBuffer_get_CALL_INSTANCE;

typedef struct _CMOCK_cirBuffer_getBlock_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int CallOrder;
  CirBuffer* Expected_me;
  unsigned char* Expected_destBlock;
  int Expected_nElem;
  int IgnoreArg_me;
  int IgnoreArg_destBlock;
  int IgnoreArg_nElem;

} CMOCK_cirBuffer_getBlock_CALL_INSTANCE;

static struct Mock_CirBufferInstance
{
  int cirBuffer_init_IgnoreBool;
  int cirBuffer_init_FinalReturn;
  CMOCK_cirBuffer_init_CALLBACK cirBuffer_init_CallbackFunctionPointer;
  int cirBuffer_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cirBuffer_init_CallInstance;
  int cirBuffer_put_IgnoreBool;
  int cirBuffer_put_FinalReturn;
  CMOCK_cirBuffer_put_CALLBACK cirBuffer_put_CallbackFunctionPointer;
  int cirBuffer_put_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cirBuffer_put_CallInstance;
  int cirBuffer_get_IgnoreBool;
  int cirBuffer_get_FinalReturn;
  CMOCK_cirBuffer_get_CALLBACK cirBuffer_get_CallbackFunctionPointer;
  int cirBuffer_get_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cirBuffer_get_CallInstance;
  int cirBuffer_getBlock_IgnoreBool;
  int cirBuffer_getBlock_FinalReturn;
  CMOCK_cirBuffer_getBlock_CALLBACK cirBuffer_getBlock_CallbackFunctionPointer;
  int cirBuffer_getBlock_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE cirBuffer_getBlock_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void Mock_CirBuffer_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.cirBuffer_init_IgnoreBool)
    Mock.cirBuffer_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_cirBuffer_init);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cirBuffer_init_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.cirBuffer_init_CallbackFunctionPointer != NULL)
    Mock.cirBuffer_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cirBuffer_put_IgnoreBool)
    Mock.cirBuffer_put_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_cirBuffer_put);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cirBuffer_put_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.cirBuffer_put_CallbackFunctionPointer != NULL)
    Mock.cirBuffer_put_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cirBuffer_get_IgnoreBool)
    Mock.cirBuffer_get_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_cirBuffer_get);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cirBuffer_get_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.cirBuffer_get_CallbackFunctionPointer != NULL)
    Mock.cirBuffer_get_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.cirBuffer_getBlock_IgnoreBool)
    Mock.cirBuffer_getBlock_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_cirBuffer_getBlock);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.cirBuffer_getBlock_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.cirBuffer_getBlock_CallbackFunctionPointer != NULL)
    Mock.cirBuffer_getBlock_CallInstance = CMOCK_GUTS_NONE;
}

void Mock_CirBuffer_Init(void)
{
  Mock_CirBuffer_Destroy();
}

void Mock_CirBuffer_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.cirBuffer_init_CallbackFunctionPointer = NULL;
  Mock.cirBuffer_init_CallbackCalls = 0;
  Mock.cirBuffer_put_CallbackFunctionPointer = NULL;
  Mock.cirBuffer_put_CallbackCalls = 0;
  Mock.cirBuffer_get_CallbackFunctionPointer = NULL;
  Mock.cirBuffer_get_CallbackCalls = 0;
  Mock.cirBuffer_getBlock_CallbackFunctionPointer = NULL;
  Mock.cirBuffer_getBlock_CallbackCalls = 0;
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

int cirBuffer_init(CirBuffer* const me, unsigned char* sto, int elemSize, int nElem)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cirBuffer_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_cirBuffer_init);
  cmock_call_instance = (CMOCK_cirBuffer_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cirBuffer_init_CallInstance);
  Mock.cirBuffer_init_CallInstance = CMock_Guts_MemNext(Mock.cirBuffer_init_CallInstance);
  if (Mock.cirBuffer_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.cirBuffer_init_FinalReturn;
    Mock.cirBuffer_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_SET_DETAILS(CMockString_cirBuffer_init,CMockString_me);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_me, me, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_sto)
  {
    UNITY_SET_DETAILS(CMockString_cirBuffer_init,CMockString_sto);
    if (cmock_call_instance->Expected_sto == NULL)
      { UNITY_TEST_ASSERT_NULL(sto, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_sto, sto, 1, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_elemSize)
  {
    UNITY_SET_DETAILS(CMockString_cirBuffer_init,CMockString_elemSize);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_elemSize, elemSize, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_nElem)
  {
    UNITY_SET_DETAILS(CMockString_cirBuffer_init,CMockString_nElem);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_nElem, nElem, cmock_line, CMockStringMismatch);
  }
  if (Mock.cirBuffer_init_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.cirBuffer_init_CallbackFunctionPointer(me, sto, elemSize, nElem, Mock.cirBuffer_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cirBuffer_init(CMOCK_cirBuffer_init_CALL_INSTANCE* cmock_call_instance, CirBuffer* const me, unsigned char* sto, int elemSize, int nElem)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
  memcpy(&cmock_call_instance->Expected_sto, &sto, sizeof(unsigned char*));
  cmock_call_instance->IgnoreArg_sto = 0;
  cmock_call_instance->Expected_elemSize = elemSize;
  cmock_call_instance->IgnoreArg_elemSize = 0;
  cmock_call_instance->Expected_nElem = nElem;
  cmock_call_instance->IgnoreArg_nElem = 0;
}

void cirBuffer_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cirBuffer_init_CALL_INSTANCE));
  CMOCK_cirBuffer_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cirBuffer_init_CallInstance = CMock_Guts_MemChain(Mock.cirBuffer_init_CallInstance, cmock_guts_index);
  Mock.cirBuffer_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cirBuffer_init_IgnoreBool = (int)1;
}

void cirBuffer_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CirBuffer* const me, unsigned char* sto, int elemSize, int nElem, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cirBuffer_init_CALL_INSTANCE));
  CMOCK_cirBuffer_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cirBuffer_init_CallInstance = CMock_Guts_MemChain(Mock.cirBuffer_init_CallInstance, cmock_guts_index);
  Mock.cirBuffer_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_cirBuffer_init(cmock_call_instance, me, sto, elemSize, nElem);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void cirBuffer_init_StubWithCallback(CMOCK_cirBuffer_init_CALLBACK Callback)
{
  Mock.cirBuffer_init_IgnoreBool = (int)0;
  Mock.cirBuffer_init_CallbackFunctionPointer = Callback;
}

void cirBuffer_init_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_cirBuffer_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.cirBuffer_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_me = 1;
}

void cirBuffer_init_CMockIgnoreArg_sto(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_cirBuffer_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.cirBuffer_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sto = 1;
}

void cirBuffer_init_CMockIgnoreArg_elemSize(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_cirBuffer_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.cirBuffer_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_elemSize = 1;
}

void cirBuffer_init_CMockIgnoreArg_nElem(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_cirBuffer_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.cirBuffer_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_nElem = 1;
}

int cirBuffer_put(CirBuffer* const me, unsigned char* elem)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cirBuffer_put_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_cirBuffer_put);
  cmock_call_instance = (CMOCK_cirBuffer_put_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cirBuffer_put_CallInstance);
  Mock.cirBuffer_put_CallInstance = CMock_Guts_MemNext(Mock.cirBuffer_put_CallInstance);
  if (Mock.cirBuffer_put_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.cirBuffer_put_FinalReturn;
    Mock.cirBuffer_put_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_SET_DETAILS(CMockString_cirBuffer_put,CMockString_me);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_me, me, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_elem)
  {
    UNITY_SET_DETAILS(CMockString_cirBuffer_put,CMockString_elem);
    if (cmock_call_instance->Expected_elem == NULL)
      { UNITY_TEST_ASSERT_NULL(elem, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_elem, elem, 1, cmock_line, CMockStringMismatch); }
  }
  if (Mock.cirBuffer_put_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.cirBuffer_put_CallbackFunctionPointer(me, elem, Mock.cirBuffer_put_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cirBuffer_put(CMOCK_cirBuffer_put_CALL_INSTANCE* cmock_call_instance, CirBuffer* const me, unsigned char* elem)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
  memcpy(&cmock_call_instance->Expected_elem, &elem, sizeof(unsigned char*));
  cmock_call_instance->IgnoreArg_elem = 0;
}

void cirBuffer_put_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cirBuffer_put_CALL_INSTANCE));
  CMOCK_cirBuffer_put_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_put_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cirBuffer_put_CallInstance = CMock_Guts_MemChain(Mock.cirBuffer_put_CallInstance, cmock_guts_index);
  Mock.cirBuffer_put_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cirBuffer_put_IgnoreBool = (int)1;
}

void cirBuffer_put_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CirBuffer* const me, unsigned char* elem, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cirBuffer_put_CALL_INSTANCE));
  CMOCK_cirBuffer_put_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_put_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cirBuffer_put_CallInstance = CMock_Guts_MemChain(Mock.cirBuffer_put_CallInstance, cmock_guts_index);
  Mock.cirBuffer_put_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_cirBuffer_put(cmock_call_instance, me, elem);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void cirBuffer_put_StubWithCallback(CMOCK_cirBuffer_put_CALLBACK Callback)
{
  Mock.cirBuffer_put_IgnoreBool = (int)0;
  Mock.cirBuffer_put_CallbackFunctionPointer = Callback;
}

void cirBuffer_put_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_cirBuffer_put_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_put_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.cirBuffer_put_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_me = 1;
}

void cirBuffer_put_CMockIgnoreArg_elem(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_cirBuffer_put_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_put_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.cirBuffer_put_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_elem = 1;
}

int cirBuffer_get(CirBuffer* const me, unsigned char* elem)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cirBuffer_get_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_cirBuffer_get);
  cmock_call_instance = (CMOCK_cirBuffer_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cirBuffer_get_CallInstance);
  Mock.cirBuffer_get_CallInstance = CMock_Guts_MemNext(Mock.cirBuffer_get_CallInstance);
  if (Mock.cirBuffer_get_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.cirBuffer_get_FinalReturn;
    Mock.cirBuffer_get_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_SET_DETAILS(CMockString_cirBuffer_get,CMockString_me);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_me, me, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_elem)
  {
    UNITY_SET_DETAILS(CMockString_cirBuffer_get,CMockString_elem);
    if (cmock_call_instance->Expected_elem == NULL)
      { UNITY_TEST_ASSERT_NULL(elem, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_elem, elem, 1, cmock_line, CMockStringMismatch); }
  }
  if (Mock.cirBuffer_get_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.cirBuffer_get_CallbackFunctionPointer(me, elem, Mock.cirBuffer_get_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cirBuffer_get(CMOCK_cirBuffer_get_CALL_INSTANCE* cmock_call_instance, CirBuffer* const me, unsigned char* elem)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
  memcpy(&cmock_call_instance->Expected_elem, &elem, sizeof(unsigned char*));
  cmock_call_instance->IgnoreArg_elem = 0;
}

void cirBuffer_get_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cirBuffer_get_CALL_INSTANCE));
  CMOCK_cirBuffer_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cirBuffer_get_CallInstance = CMock_Guts_MemChain(Mock.cirBuffer_get_CallInstance, cmock_guts_index);
  Mock.cirBuffer_get_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cirBuffer_get_IgnoreBool = (int)1;
}

void cirBuffer_get_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CirBuffer* const me, unsigned char* elem, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cirBuffer_get_CALL_INSTANCE));
  CMOCK_cirBuffer_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cirBuffer_get_CallInstance = CMock_Guts_MemChain(Mock.cirBuffer_get_CallInstance, cmock_guts_index);
  Mock.cirBuffer_get_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_cirBuffer_get(cmock_call_instance, me, elem);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void cirBuffer_get_StubWithCallback(CMOCK_cirBuffer_get_CALLBACK Callback)
{
  Mock.cirBuffer_get_IgnoreBool = (int)0;
  Mock.cirBuffer_get_CallbackFunctionPointer = Callback;
}

void cirBuffer_get_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_cirBuffer_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.cirBuffer_get_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_me = 1;
}

void cirBuffer_get_CMockIgnoreArg_elem(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_cirBuffer_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.cirBuffer_get_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_elem = 1;
}

int cirBuffer_getBlock(CirBuffer* const me, unsigned char* destBlock, int nElem)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_cirBuffer_getBlock_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_cirBuffer_getBlock);
  cmock_call_instance = (CMOCK_cirBuffer_getBlock_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.cirBuffer_getBlock_CallInstance);
  Mock.cirBuffer_getBlock_CallInstance = CMock_Guts_MemNext(Mock.cirBuffer_getBlock_CallInstance);
  if (Mock.cirBuffer_getBlock_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.cirBuffer_getBlock_FinalReturn;
    Mock.cirBuffer_getBlock_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_SET_DETAILS(CMockString_cirBuffer_getBlock,CMockString_me);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_me, me, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_destBlock)
  {
    UNITY_SET_DETAILS(CMockString_cirBuffer_getBlock,CMockString_destBlock);
    if (cmock_call_instance->Expected_destBlock == NULL)
      { UNITY_TEST_ASSERT_NULL(destBlock, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_destBlock, destBlock, 1, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_nElem)
  {
    UNITY_SET_DETAILS(CMockString_cirBuffer_getBlock,CMockString_nElem);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_nElem, nElem, cmock_line, CMockStringMismatch);
  }
  if (Mock.cirBuffer_getBlock_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.cirBuffer_getBlock_CallbackFunctionPointer(me, destBlock, nElem, Mock.cirBuffer_getBlock_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_cirBuffer_getBlock(CMOCK_cirBuffer_getBlock_CALL_INSTANCE* cmock_call_instance, CirBuffer* const me, unsigned char* destBlock, int nElem)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
  memcpy(&cmock_call_instance->Expected_destBlock, &destBlock, sizeof(unsigned char*));
  cmock_call_instance->IgnoreArg_destBlock = 0;
  cmock_call_instance->Expected_nElem = nElem;
  cmock_call_instance->IgnoreArg_nElem = 0;
}

void cirBuffer_getBlock_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cirBuffer_getBlock_CALL_INSTANCE));
  CMOCK_cirBuffer_getBlock_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_getBlock_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cirBuffer_getBlock_CallInstance = CMock_Guts_MemChain(Mock.cirBuffer_getBlock_CallInstance, cmock_guts_index);
  Mock.cirBuffer_getBlock_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.cirBuffer_getBlock_IgnoreBool = (int)1;
}

void cirBuffer_getBlock_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, CirBuffer* const me, unsigned char* destBlock, int nElem, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_cirBuffer_getBlock_CALL_INSTANCE));
  CMOCK_cirBuffer_getBlock_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_getBlock_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.cirBuffer_getBlock_CallInstance = CMock_Guts_MemChain(Mock.cirBuffer_getBlock_CallInstance, cmock_guts_index);
  Mock.cirBuffer_getBlock_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_cirBuffer_getBlock(cmock_call_instance, me, destBlock, nElem);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void cirBuffer_getBlock_StubWithCallback(CMOCK_cirBuffer_getBlock_CALLBACK Callback)
{
  Mock.cirBuffer_getBlock_IgnoreBool = (int)0;
  Mock.cirBuffer_getBlock_CallbackFunctionPointer = Callback;
}

void cirBuffer_getBlock_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_cirBuffer_getBlock_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_getBlock_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.cirBuffer_getBlock_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_me = 1;
}

void cirBuffer_getBlock_CMockIgnoreArg_destBlock(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_cirBuffer_getBlock_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_getBlock_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.cirBuffer_getBlock_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_destBlock = 1;
}

void cirBuffer_getBlock_CMockIgnoreArg_nElem(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_cirBuffer_getBlock_CALL_INSTANCE* cmock_call_instance = (CMOCK_cirBuffer_getBlock_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.cirBuffer_getBlock_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_nElem = 1;
}

